/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily cost by service, provider, or allocation
         * @description Total daily BilledCost per selected grouping key, plus per-day and period totals. groupBy=service uses FOCUS ServiceName; groupBy=provider uses FOCUS ServiceProviderName; groupBy=allocation applies the query-time cost-allocation rules (virtual tagging) and keys each cost by its allocation label, with cost matching no rule under "Unallocated". Ordering is deterministic: days ascending, keys sorted by name. Costs are decimal strings — never floats — so no precision is lost.
         */
        get: operations["getDailyCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Period cost summary with optional preceding-window comparison
         * @description Period totals by grouping key for the requested [start, end] window, plus an optional preceding-window comparison computed server-side. groupBy semantics and validation match /api/v1/costs/daily (service / provider / allocation; allocation unconfigured → 400; malformed rules → 500). All money values are exact decimal strings (never floats). The response `total` equals /api/v1/costs/daily's period total for identical params. Keys are ordered total-desc, then key-asc.
         *     Preceding window: prevEnd = start − 1 day, prevStart = prevEnd − (end − start). ALL previous-window fields (previousTotal, previousStart, previousEnd, and every keys[].previousTotal / keys[].delta) are ABSENT together — never null or "" — when the preceding window is UNDEFINED: (i) start or end is unbounded/empty; (ii) the preceding-window query returns zero cost rows (it predates all ingested data); (iii) the preceding window's single currency differs from the current window's (a cross-currency delta is never computed — the per-window single-currency guard cannot catch a currency switch BETWEEN windows). Never emit previousTotal "0" for a data-empty preceding window. A store error from either window — including the mixed-currency guard tripping WITHIN the preceding window — is a 500, mirroring /costs/daily.
         *     When the preceding window is DEFINED, every key carries delta = total − previousTotal (exact decimal.Sub); keys absent from the previous window omit previousTotal while delta equals total (previousTotal-absence alone marks newness). "Gone" keys (present only in the previous window) are out of scope for this version. Empty CURRENT window: total "0", keys [] (never null). No share field — client Number() geometry only.
         */
        get: operations["getCostsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statistical cost anomalies (spikes and dips)
         * @description Flags spikes and dips in the daily cost series with a robust median/MAD detector computed at QUERY time — stateless, so retroactive FOCUS corrections are automatically re-scored. Uses the SAME groupBy dimensions as /api/v1/costs/daily and scores both the per-day TOTAL series (the sum over the day's keys) and each grouping key's own series. Flags are range-INDEPENDENT: the full stored history up to the requested end is scored, then only flags whose day falls inside [start, end] are returned, so a given day yields the identical flag regardless of the queried start. Because scoring reads full history, a mixed-currency HISTORY returns 500 on the single-currency guard even when the requested range alone is single-currency. Every statistic is an exact decimal string and the detector's fixed parameters are echoed, so each flag is hand-recomputable.
         */
        get: operations["getAnomalies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/tokens/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily token usage by service
         * @description Total daily token ConsumedQuantity per service, for the default tenant. Scoped to token usage: only enriched rows whose ConsumedUnit is "Tokens" appear. A row whose ConsumedQuantity is null (money-only rows — credits, undifferentiated call fees, unmatched usage) is skipped, never surfaced with a zero or fabricated quantity, and non-token FOCUS usage quantities are excluded. Ordering is deterministic: day ascending, then serviceName, then consumedUnit. Quantities are exact decimal strings — never floats — so a large token count loses no precision.
         */
        get: operations["getDailyTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported business metrics
         * @description Lists the default tenant's user-authored business metrics and their inclusive stored day spans, sorted by name. These business-value counts are separate from vendor usage metrics and never appear in the AI Usage endpoint.
         */
        get: operations["getBusinessMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unit-economics/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily and period unit economics for one business metric
         * @description Merges exact daily BilledCost with one imported business metric. A day is covered only when both a cost total (of any sign) and a positive quantity exist. Period cost and quantity aggregate covered days only. unitCost is derived in Go as cost / quantity rounded to scale 18, round-half-away-from-zero, then rendered as a decimal string with trailing zeros trimmed. A rendered "0" means the exact quotient rounds to zero at scale 18. Ratios are derived on read and never stored.
         */
        get: operations["getDailyUnitEconomics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/metrics/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily cost-orphaned usage metrics
         * @description Total daily quantity per service, tier, metric, and unit, for the default tenant. These are the cost-orphaned usage metrics the AI-vendor connectors fetch but that carry no money on the vendor's cost report (Anthropic priority/flex-tier tokens and web-search request counts; standard/batch usage keys no cost row referenced; OpenAI recognized-but-unpriced line items). They live OUTSIDE the FOCUS cost dataset, so they never appear in the daily-cost or daily-token views and never contribute to any cost or token total. Ordering is deterministic: day ascending, then serviceName, serviceTier, metricName, unit. Quantities are exact decimal strings — never floats. serviceTier is "" when the vendor has no tier concept.
         */
        get: operations["getDailyUsageMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /**
             * @description Service name.
             * @example costroid
             */
            name: string;
            /**
             * @description Version of the running Costroid binary.
             * @example 0.1.0-dev
             */
            version: string;
            /**
             * @description FOCUS specification version the internal model targets (decision D4).
             * @example 1.4
             */
            focusVersion: string;
            /**
             * @description True only for the isolated, synthetic, read-only product demo.
             * @example false
             */
            demo: boolean;
        };
        DailyCosts: {
            /**
             * @description Billing currency of all listed costs (FOCUS BillingCurrency). Empty when no data matched the requested period.
             * @example USD
             */
            currency: string;
            /** @description One entry per calendar day with data, days ascending. */
            days: components["schemas"]["DailyCost"][];
            /**
             * @description Total cost of the whole period, as a decimal string.
             * @example 32.7663
             */
            total: string;
        };
        CostsSummary: {
            /**
             * @description Billing currency of the CURRENT window (FOCUS BillingCurrency). Empty when the current window has no cost rows.
             * @example USD
             */
            currency: string;
            /**
             * @description Period total for the current window as a decimal string. Equals /api/v1/costs/daily's period total for identical params. "0" when the current window is empty.
             * @example 964050.632653589793238462
             */
            total: string;
            /**
             * @description Period total of the preceding window as a decimal string. Present only when the preceding window is defined (see path description); omitted entirely otherwise — never null or "0" for an undefined window.
             * @example 120000.50
             */
            previousTotal?: string;
            /**
             * Format: date
             * @description Inclusive first day of the preceding window. Present exactly when previousTotal is present.
             * @example 2025-12-13
             */
            previousStart?: string;
            /**
             * Format: date
             * @description Inclusive last day of the preceding window. Present exactly when previousTotal is present.
             * @example 2026-01-11
             */
            previousEnd?: string;
            /** @description Per-key period totals for the current window, ordered total-desc then key-asc. Never null; [] when the current window is empty. Gone keys (previous-only) are out of scope. */
            keys: components["schemas"]["CostSummaryKey"][];
        };
        CostSummaryKey: {
            /**
             * @description Grouping key (ServiceName / ServiceProviderName / allocation label).
             * @example Amazon Web Services
             */
            key: string;
            /**
             * @description Period total for this key in the current window, as a decimal string.
             * @example 3141.592653589793238462
             */
            total: string;
            /**
             * @description Period total for this key in the preceding window. Present only when the preceding window is defined AND the key had cost there; omitted for new keys (delta then equals total) and when the window is undefined.
             * @example 2800.00
             */
            previousTotal?: string;
            /**
             * @description Exact total − previousTotal (decimal.Sub). Present on EVERY key when the preceding window is defined; omitted on every key when undefined. For a new key (no previousTotal), delta equals total.
             * @example 341.592653589793238462
             */
            delta?: string;
        };
        DailyCost: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-06-01
             */
            date: string;
            /**
             * @description Total cost of the day, as a decimal string.
             * @example 4.6809
             */
            total: string;
            /** @description Per-group costs, sorted by grouping key. */
            services: components["schemas"]["ServiceCost"][];
        };
        ServiceCost: {
            /**
             * @description Grouping key: FOCUS ServiceName (groupBy=service), FOCUS ServiceProviderName (groupBy=provider), or the allocation label (groupBy=allocation; cost matching no rule appears under "Unallocated").
             * @example Amazon Elastic Compute Cloud
             */
            key: string;
            /**
             * @description Cost total, as a decimal string.
             * @example 2.4192
             */
            cost: string;
        };
        Anomalies: {
            /**
             * @description Billing currency of the scored costs (FOCUS BillingCurrency). Empty when no data matched.
             * @example USD
             */
            currency: string;
            parameters: components["schemas"]["AnomalyParameters"];
            /** @description Detected flags, ordered date-ascending, then total scope before key scope, then key-ascending. Never null; [] when nothing is flagged. */
            anomalies: components["schemas"]["Anomaly"][];
        };
        AnomalyParameters: {
            /**
             * @description Strict-threshold multiple of the scaled MAD, as a decimal string.
             * @example 3
             */
            k: string;
            /**
             * @description MAD-to-sigma consistency constant (R stats::mad), as a decimal string.
             * @example 1.4826
             */
            consistencyConstant: string;
            /**
             * @description Maximum trailing observed days in the baseline window.
             * @example 30
             */
            windowDays: number;
            /**
             * @description Minimum baseline observations required to score a day.
             * @example 10
             */
            minObservations: number;
            /**
             * @description Fraction of the absolute median a deviation must also reach, as a decimal string.
             * @example 0.1
             */
            relativeFloor: string;
            /**
             * @description The grouping dimension echoed verbatim from the request.
             * @example service
             */
            groupBy: string;
        };
        Anomaly: {
            /**
             * Format: date
             * @description The UTC calendar day flagged.
             * @example 2026-06-18
             */
            date: string;
            /**
             * @description "total" (the summed daily series) or "key" (one grouping key's series).
             * @example total
             */
            scope: string;
            /**
             * @description The grouping key whose series flagged; present ONLY when scope is "key" (never for "total", so a real key literally named "total" is unambiguous).
             * @example Amazon Elastic Compute Cloud
             */
            key?: string;
            /**
             * @description "increase" when observed is above the median, "decrease" when below.
             * @example increase
             */
            direction: string;
            /**
             * @description The day's observed value, as an exact decimal string.
             * @example 31.2
             */
            observed: string;
            /**
             * @description Baseline median, as an exact decimal string.
             * @example 4.6809
             */
            median: string;
            /**
             * @description Baseline median absolute deviation, as an exact decimal string.
             * @example 0.0013
             */
            mad: string;
            /**
             * @description mad times consistencyConstant, as an exact decimal string.
             * @example 0.00192738
             */
            scaledMad: string;
            /**
             * @description k times scaledMad — the strict flag threshold, as an exact decimal string.
             * @example 0.00578214
             */
            threshold: string;
            /**
             * @description The absolute difference of observed and median, as a decimal string.
             * @example 26.5191
             */
            deviation: string;
        };
        DailyTokenUsage: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-05-01
             */
            date: string;
            /**
             * @description FOCUS ServiceName.
             * @example OpenAI API
             */
            serviceName: string;
            /**
             * @description FOCUS ConsumedUnit (always "Tokens" today).
             * @example Tokens
             */
            consumedUnit: string;
            /**
             * @description Total ConsumedQuantity for the day/service/unit, as an exact decimal string — never a float.
             * @example 1500000
             */
            consumedQuantity: string;
        };
        DailyUsageMetric: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-05-01
             */
            date: string;
            /**
             * @description Service or model identity.
             * @example claude-opus-4-6
             */
            serviceName: string;
            /**
             * @description Vendor service tier, or "" when the vendor has no tier concept.
             * @example priority
             */
            serviceTier: string;
            /**
             * @description Frozen metric identifier (a token_type, "web_search_requests", or an opaque line item).
             * @example uncached_input_tokens
             */
            metricName: string;
            /**
             * @description Frozen unit vocabulary: "Tokens", "Requests", or "Unknown".
             * @example Tokens
             */
            unit: string;
            /**
             * @description Total quantity for the day/service/tier/metric/unit, as an exact decimal string — never a float.
             * @example 999
             */
            quantity: string;
        };
        BusinessMetrics: {
            /** @description Imported business metrics, sorted by name; never null. */
            metrics: components["schemas"]["BusinessMetricInfo"][];
        };
        BusinessMetricInfo: {
            /**
             * @description Exact metric identity used by the unit-economics query.
             * @example requests served
             */
            name: string;
            /**
             * Format: date
             * @description First stored UTC calendar day.
             * @example 2026-05-01
             */
            firstDay: string;
            /**
             * Format: date
             * @description Last stored UTC calendar day.
             * @example 2026-05-31
             */
            lastDay: string;
        };
        UnitEconomics: {
            /** @example requests served */
            metric: string;
            /**
             * @description Cost-side BillingCurrency; empty when no cost matched.
             * @example USD
             */
            currency: string;
            /** @description Union of cost and metric days, day-ascending. */
            days: components["schemas"]["UnitEconomicsDay"][];
            period: components["schemas"]["UnitEconomicsPeriod"];
        };
        UnitEconomicsDay: {
            /** Format: date */
            date: string;
            /** @description Exact daily cost when a cost bin exists; any sign is retained. */
            cost?: string;
            /** @description Exact daily business quantity when a metric bin exists. */
            quantity?: string;
            /** @description Present only for a covered day. cost / quantity rounded to scale 18 with round-half-away-from-zero, trailing zeros trimmed. "0" is a meaningful rounded result and is not omitted. */
            unitCost?: string;
        };
        UnitEconomicsPeriod: {
            /** @description Number of days carrying both cost and positive quantity. */
            coveredDays: number;
            /** @description Exact cost sum over covered days only. */
            cost: string;
            /** @description Exact quantity sum over covered days only. */
            quantity: string;
            /** @description Covered-period cost / quantity at scale 18, round-half-away-from-zero; absent when coveredDays is zero. */
            unitCost?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata about this Costroid instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    getDailyCosts: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
                /** @description Cost grouping dimension. */
                groupBy?: "service" | "provider" | "allocation";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily costs grouped by the requested dimension for the requested period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCosts"];
                };
            };
            /** @description Invalid start date, end date, or groupBy value; or groupBy=allocation was requested but no allocation rules are configured or the rules file was not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The cost query failed, including an unreadable, malformed, or invalid allocation rules file (reported as "loading allocation rules: …"). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getCostsSummary: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) of the CURRENT window. Defaults to the full range of stored data. Unbounded start makes the preceding window undefined. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) of the CURRENT window. Defaults to the full range of stored data. Unbounded end makes the preceding window undefined. */
                end?: string;
                /** @description Cost grouping dimension (same set as /api/v1/costs/daily). */
                groupBy?: "service" | "provider" | "allocation";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Period cost summary for the requested window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostsSummary"];
                };
            };
            /** @description Invalid start date, end date, or groupBy value; or groupBy=allocation was requested but no allocation rules are configured or the rules file was not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The cost query failed (including mixed currencies within a window or an unreadable/malformed/invalid allocation rules file). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getAnomalies: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) of the RETURNED flags; it does not affect the scoring baseline. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to score and return. Defaults to the full range of stored data. */
                end?: string;
                /** @description Cost grouping dimension (the same set as /api/v1/costs/daily). */
                groupBy?: "service" | "provider" | "allocation";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detected anomalies for the requested period; [] when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anomalies"];
                };
            };
            /** @description Invalid start date, end date, or groupBy value; or groupBy=allocation was requested but no allocation rules are configured or the rules file was not found. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The cost query failed, including a mixed-currency history or an unreadable, malformed, or invalid allocation rules file. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getDailyTokens: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily token usage grouped by service and unit for the requested period, day-ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyTokenUsage"][];
                };
            };
            /** @description Invalid start or end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getBusinessMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business metric names and available day spans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessMetrics"];
                };
            };
            /** @description The business-metric list query failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getDailyUnitEconomics: {
        parameters: {
            query: {
                /** @description Exact imported business metric name. */
                metric: string;
                /** @description Inclusive first UTC calendar day; defaults to unbounded. */
                start?: string;
                /** @description Inclusive last UTC calendar day; defaults to unbounded. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily gaps and covered-only period unit economics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitEconomics"];
                };
            };
            /** @description Missing or empty metric, or an invalid start/end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The named business metric has never been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description A cost or business-metric store query failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getDailyUsageMetrics: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily usage metrics grouped by service, tier, metric, and unit for the requested period, day-ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyUsageMetric"][];
                };
            };
            /** @description Invalid start or end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
