/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance metadata */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily cost by service
         * @description Total daily BilledCost per service, plus per-day and period totals. Ordering is deterministic: days ascending, services sorted by name. Costs are decimal strings — never floats — so no precision is lost.
         */
        get: operations["getDailyCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/tokens/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily token usage by service
         * @description Total daily token ConsumedQuantity per service, for the default tenant. Scoped to token usage: only enriched rows whose ConsumedUnit is "Tokens" appear. A row whose ConsumedQuantity is null (money-only rows — credits, undifferentiated call fees, unmatched usage) is skipped, never surfaced with a zero or fabricated quantity, and non-token FOCUS usage quantities are excluded. Ordering is deterministic: day ascending, then serviceName, then consumedUnit. Quantities are exact decimal strings — never floats — so a large token count loses no precision.
         */
        get: operations["getDailyTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/metrics/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily cost-orphaned usage metrics
         * @description Total daily quantity per service, tier, metric, and unit, for the default tenant. These are the cost-orphaned usage metrics the AI-vendor connectors fetch but that carry no money on the vendor's cost report (Anthropic priority/flex-tier tokens and web-search request counts; standard/batch usage keys no cost row referenced; OpenAI recognized-but-unpriced line items). They live OUTSIDE the FOCUS cost dataset, so they never appear in the daily-cost or daily-token views and never contribute to any cost or token total. Ordering is deterministic: day ascending, then serviceName, serviceTier, metricName, unit. Quantities are exact decimal strings — never floats. serviceTier is "" when the vendor has no tier concept.
         */
        get: operations["getDailyUsageMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /**
             * @description Service name.
             * @example costroid
             */
            name: string;
            /**
             * @description Version of the running Costroid binary.
             * @example 0.1.0-dev
             */
            version: string;
            /**
             * @description FOCUS specification version the internal model targets (decision D4).
             * @example 1.4
             */
            focusVersion: string;
        };
        DailyCosts: {
            /**
             * @description Billing currency of all listed costs (FOCUS BillingCurrency). Empty when no data matched the requested period.
             * @example USD
             */
            currency: string;
            /** @description One entry per calendar day with data, days ascending. */
            days: components["schemas"]["DailyCost"][];
            /**
             * @description Total cost of the whole period, as a decimal string.
             * @example 32.7663
             */
            total: string;
        };
        DailyCost: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-06-01
             */
            date: string;
            /**
             * @description Total cost of the day, as a decimal string.
             * @example 4.6809
             */
            total: string;
            /** @description Per-service costs, sorted by service name. */
            services: components["schemas"]["ServiceCost"][];
        };
        ServiceCost: {
            /**
             * @description FOCUS ServiceName.
             * @example Amazon Elastic Compute Cloud
             */
            serviceName: string;
            /**
             * @description Cost total, as a decimal string.
             * @example 2.4192
             */
            cost: string;
        };
        DailyTokenUsage: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-05-01
             */
            date: string;
            /**
             * @description FOCUS ServiceName.
             * @example OpenAI API
             */
            serviceName: string;
            /**
             * @description FOCUS ConsumedUnit (always "Tokens" today).
             * @example Tokens
             */
            consumedUnit: string;
            /**
             * @description Total ConsumedQuantity for the day/service/unit, as an exact decimal string — never a float.
             * @example 1500000
             */
            consumedQuantity: string;
        };
        DailyUsageMetric: {
            /**
             * Format: date
             * @description The UTC calendar day.
             * @example 2026-05-01
             */
            date: string;
            /**
             * @description Service or model identity.
             * @example claude-opus-4-6
             */
            serviceName: string;
            /**
             * @description Vendor service tier, or "" when the vendor has no tier concept.
             * @example priority
             */
            serviceTier: string;
            /**
             * @description Frozen metric identifier (a token_type, "web_search_requests", or an opaque line item).
             * @example uncached_input_tokens
             */
            metricName: string;
            /**
             * @description Frozen unit vocabulary: "Tokens", "Requests", or "Unknown".
             * @example Tokens
             */
            unit: string;
            /**
             * @description Total quantity for the day/service/tier/metric/unit, as an exact decimal string — never a float.
             * @example 999
             */
            quantity: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata about this Costroid instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    getDailyCosts: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily costs grouped by service for the requested period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCosts"];
                };
            };
            /** @description Invalid start or end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getDailyTokens: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily token usage grouped by service and unit for the requested period, day-ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyTokenUsage"][];
                };
            };
            /** @description Invalid start or end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getDailyUsageMetrics: {
        parameters: {
            query?: {
                /** @description Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data. */
                start?: string;
                /** @description Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data. */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily usage metrics grouped by service, tier, metric, and unit for the requested period, day-ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyUsageMetric"][];
                };
            };
            /** @description Invalid start or end date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
