//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SyncLastRunOutcome.
const (
	Error   SyncLastRunOutcome = "error"
	Partial SyncLastRunOutcome = "partial"
	Success SyncLastRunOutcome = "success"
)

// Valid indicates whether the value is a known member of the SyncLastRunOutcome enum.
func (e SyncLastRunOutcome) Valid() bool {
	switch e {
	case Error:
		return true
	case Partial:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for GetAnomaliesParamsGroupBy.
const (
	GetAnomaliesParamsGroupByAllocation GetAnomaliesParamsGroupBy = "allocation"
	GetAnomaliesParamsGroupByProvider   GetAnomaliesParamsGroupBy = "provider"
	GetAnomaliesParamsGroupByRegion     GetAnomaliesParamsGroupBy = "region"
	GetAnomaliesParamsGroupByService    GetAnomaliesParamsGroupBy = "service"
	GetAnomaliesParamsGroupBySubaccount GetAnomaliesParamsGroupBy = "subaccount"
	GetAnomaliesParamsGroupByTag        GetAnomaliesParamsGroupBy = "tag"
)

// Valid indicates whether the value is a known member of the GetAnomaliesParamsGroupBy enum.
func (e GetAnomaliesParamsGroupBy) Valid() bool {
	switch e {
	case GetAnomaliesParamsGroupByAllocation:
		return true
	case GetAnomaliesParamsGroupByProvider:
		return true
	case GetAnomaliesParamsGroupByRegion:
		return true
	case GetAnomaliesParamsGroupByService:
		return true
	case GetAnomaliesParamsGroupBySubaccount:
		return true
	case GetAnomaliesParamsGroupByTag:
		return true
	default:
		return false
	}
}

// Defines values for GetDailyCostsParamsGroupBy.
const (
	GetDailyCostsParamsGroupByAllocation GetDailyCostsParamsGroupBy = "allocation"
	GetDailyCostsParamsGroupByProvider   GetDailyCostsParamsGroupBy = "provider"
	GetDailyCostsParamsGroupByRegion     GetDailyCostsParamsGroupBy = "region"
	GetDailyCostsParamsGroupByService    GetDailyCostsParamsGroupBy = "service"
	GetDailyCostsParamsGroupBySubaccount GetDailyCostsParamsGroupBy = "subaccount"
	GetDailyCostsParamsGroupByTag        GetDailyCostsParamsGroupBy = "tag"
)

// Valid indicates whether the value is a known member of the GetDailyCostsParamsGroupBy enum.
func (e GetDailyCostsParamsGroupBy) Valid() bool {
	switch e {
	case GetDailyCostsParamsGroupByAllocation:
		return true
	case GetDailyCostsParamsGroupByProvider:
		return true
	case GetDailyCostsParamsGroupByRegion:
		return true
	case GetDailyCostsParamsGroupByService:
		return true
	case GetDailyCostsParamsGroupBySubaccount:
		return true
	case GetDailyCostsParamsGroupByTag:
		return true
	default:
		return false
	}
}

// Defines values for GetCostsSummaryParamsGroupBy.
const (
	Allocation GetCostsSummaryParamsGroupBy = "allocation"
	Provider   GetCostsSummaryParamsGroupBy = "provider"
	Region     GetCostsSummaryParamsGroupBy = "region"
	Service    GetCostsSummaryParamsGroupBy = "service"
	Subaccount GetCostsSummaryParamsGroupBy = "subaccount"
	Tag        GetCostsSummaryParamsGroupBy = "tag"
)

// Valid indicates whether the value is a known member of the GetCostsSummaryParamsGroupBy enum.
func (e GetCostsSummaryParamsGroupBy) Valid() bool {
	switch e {
	case Allocation:
		return true
	case Provider:
		return true
	case Region:
		return true
	case Service:
		return true
	case Subaccount:
		return true
	case Tag:
		return true
	default:
		return false
	}
}

// Anomalies defines model for Anomalies.
type Anomalies struct {
	// Anomalies Detected flags, ordered date-ascending, then total scope before key scope, then key-ascending. Never null; [] when nothing is flagged.
	Anomalies []Anomaly `json:"anomalies"`

	// Currency Billing currency of the scored costs (FOCUS BillingCurrency). Empty when no data matched.
	Currency   string            `json:"currency"`
	Parameters AnomalyParameters `json:"parameters"`
}

// Anomaly defines model for Anomaly.
type Anomaly struct {
	// Date The UTC calendar day flagged.
	Date openapi_types.Date `json:"date"`

	// Deviation The absolute difference of observed and median, as a decimal string.
	Deviation string `json:"deviation"`

	// Direction "increase" when observed is above the median, "decrease" when below.
	Direction string `json:"direction"`

	// Key The grouping key whose series flagged; present ONLY when scope is "key" (never for "total", so a real key literally named "total" is unambiguous).
	Key *string `json:"key,omitempty"`

	// Mad Baseline median absolute deviation, as an exact decimal string.
	Mad string `json:"mad"`

	// Median Baseline median, as an exact decimal string.
	Median string `json:"median"`

	// Observed The day's observed value, as an exact decimal string.
	Observed string `json:"observed"`

	// ScaledMad mad times consistencyConstant, as an exact decimal string.
	ScaledMad string `json:"scaledMad"`

	// Scope "total" (the summed daily series) or "key" (one grouping key's series).
	Scope string `json:"scope"`

	// Threshold k times scaledMad — the strict flag threshold, as an exact decimal string.
	Threshold string `json:"threshold"`
}

// AnomalyParameters defines model for AnomalyParameters.
type AnomalyParameters struct {
	// ConsistencyConstant MAD-to-sigma consistency constant (R stats::mad), as a decimal string.
	ConsistencyConstant string `json:"consistencyConstant"`

	// GroupBy The grouping dimension echoed verbatim from the request.
	GroupBy string `json:"groupBy"`

	// K Strict-threshold multiple of the scaled MAD, as a decimal string.
	K string `json:"k"`

	// MinObservations Minimum baseline observations required to score a day.
	MinObservations int `json:"minObservations"`

	// RelativeFloor Fraction of the absolute median a deviation must also reach, as a decimal string.
	RelativeFloor string `json:"relativeFloor"`

	// WindowDays Maximum trailing observed days in the baseline window.
	WindowDays int `json:"windowDays"`
}

// BusinessMetricInfo defines model for BusinessMetricInfo.
type BusinessMetricInfo struct {
	// FirstDay First stored UTC calendar day.
	FirstDay openapi_types.Date `json:"firstDay"`

	// LastDay Last stored UTC calendar day.
	LastDay openapi_types.Date `json:"lastDay"`

	// Name Exact metric identity used by the unit-economics query.
	Name string `json:"name"`
}

// BusinessMetrics defines model for BusinessMetrics.
type BusinessMetrics struct {
	// Metrics Imported business metrics, sorted by name; never null.
	Metrics []BusinessMetricInfo `json:"metrics"`
}

// CostSummaryKey defines model for CostSummaryKey.
type CostSummaryKey struct {
	// Delta Exact total − previousTotal (decimal.Sub). Present on EVERY key when the preceding window is defined; omitted on every key when undefined. For a new key (no previousTotal), delta equals total.
	Delta *string `json:"delta,omitempty"`

	// Key Grouping key: FOCUS ServiceName (groupBy=service), FOCUS ServiceProviderName (groupBy=provider), FOCUS SubAccountName (groupBy=subaccount; missing names appear under "(no subaccount)"), FOCUS RegionName (groupBy=region; missing names appear under "(no region)"), the value of the requested FOCUS Tags key (groupBy=tag; untagged cost appears under "(untagged)"), or the allocation label (groupBy=allocation).
	Key string `json:"key"`

	// PreviousTotal Period total for this key in the preceding window. Present only when the preceding window is defined AND the key had cost there; omitted for new keys (delta then equals total) and when the window is undefined.
	PreviousTotal *string `json:"previousTotal,omitempty"`

	// Total Period total for this key in the current window, as a decimal string.
	Total string `json:"total"`
}

// CostsSummary defines model for CostsSummary.
type CostsSummary struct {
	// Currencies All billing currencies with cost rows in the current window, sorted ascending. This is the source for a currency selector and is [] (never null) when the window is empty.
	Currencies []string `json:"currencies"`

	// Currency Billing currency of this response's summary (FOCUS BillingCurrency): the currency query parameter when provided, otherwise the alphabetically-first currency in the current window, or "" when the window is empty.
	Currency string `json:"currency"`

	// Keys Per-key period totals for the current window, ordered total-desc then key-asc. Never null; [] when the current window is empty. Gone keys (previous-only) are out of scope.
	Keys []CostSummaryKey `json:"keys"`

	// PreviousEnd Inclusive last day of the preceding window. Present exactly when previousTotal is present.
	PreviousEnd *openapi_types.Date `json:"previousEnd,omitempty"`

	// PreviousStart Inclusive first day of the preceding window. Present exactly when previousTotal is present.
	PreviousStart *openapi_types.Date `json:"previousStart,omitempty"`

	// PreviousTotal Period total of the preceding window as a decimal string. Present only when the preceding window is defined (see path description); omitted entirely otherwise — never null or "0" for an undefined window.
	PreviousTotal *string `json:"previousTotal,omitempty"`

	// Provider FOCUS ServiceProviderName of this response's rows: the provider query parameter when provided, otherwise "".
	Provider string `json:"provider"`

	// Providers All FOCUS ServiceProviderName values with cost rows in the requested range, not scoped by the provider or currency filters, sorted ascending. This is the source for a provider selector and is [] (never null) when the range is empty.
	Providers []string `json:"providers"`

	// Total Period total for the current window as a decimal string. Equals /api/v1/costs/daily's period total for identical params. "0" when the current window is empty.
	Total string `json:"total"`
}

// DailyCost defines model for DailyCost.
type DailyCost struct {
	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// Services Per-group costs, sorted by grouping key.
	Services []ServiceCost `json:"services"`

	// Total Total cost of the day, as a decimal string.
	Total string `json:"total"`
}

// DailyCosts defines model for DailyCosts.
type DailyCosts struct {
	// Currencies All billing currencies with cost rows in the requested range, sorted ascending. This is the source for a currency selector and is [] (never null) when the range is empty.
	Currencies []string `json:"currencies"`

	// Currency Billing currency of this response's series (FOCUS BillingCurrency): the currency query parameter when provided, otherwise the alphabetically-first currency in range, or "" when the range is empty.
	Currency string `json:"currency"`

	// Days One entry per calendar day with data, days ascending.
	Days []DailyCost `json:"days"`

	// Provider FOCUS ServiceProviderName of this response's rows: the provider query parameter when provided, otherwise "".
	Provider string `json:"provider"`

	// Providers All FOCUS ServiceProviderName values with cost rows in the requested range, not scoped by the provider or currency filters, sorted ascending. This is the source for a provider selector and is [] (never null) when the range is empty.
	Providers []string `json:"providers"`

	// Total Total cost of the whole period, as a decimal string.
	Total string `json:"total"`
}

// DailyTokenUsage defines model for DailyTokenUsage.
type DailyTokenUsage struct {
	// ConsumedQuantity Total ConsumedQuantity for the day/service/unit, as an exact decimal string — never a float.
	ConsumedQuantity string `json:"consumedQuantity"`

	// ConsumedUnit FOCUS ConsumedUnit (always "Tokens" today).
	ConsumedUnit string `json:"consumedUnit"`

	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// ServiceName FOCUS ServiceName.
	ServiceName string `json:"serviceName"`
}

// DailyUsageMetric defines model for DailyUsageMetric.
type DailyUsageMetric struct {
	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// MetricName Frozen metric identifier (a token_type, "web_search_requests", or an opaque line item).
	MetricName string `json:"metricName"`

	// Quantity Total quantity for the day/service/tier/metric/unit, as an exact decimal string — never a float.
	Quantity string `json:"quantity"`

	// ServiceName Service or model identity.
	ServiceName string `json:"serviceName"`

	// ServiceTier Vendor service tier, or "" when the vendor has no tier concept.
	ServiceTier string `json:"serviceTier"`

	// Unit Frozen unit vocabulary: "Tokens", "Requests", or "Unknown".
	Unit string `json:"unit"`
}

// Meta defines model for Meta.
type Meta struct {
	// Demo True only for the isolated, synthetic, read-only product demo.
	Demo bool `json:"demo"`

	// FocusVersion FOCUS specification version the internal model targets (decision D4).
	FocusVersion string `json:"focusVersion"`

	// Name Service name.
	Name string `json:"name"`

	// Version Version of the running Costroid binary.
	Version string `json:"version"`
}

// ServiceCost defines model for ServiceCost.
type ServiceCost struct {
	// Cost Cost total, as a decimal string.
	Cost string `json:"cost"`

	// Key Grouping key: FOCUS ServiceName (groupBy=service), FOCUS ServiceProviderName (groupBy=provider), FOCUS SubAccountName (groupBy=subaccount; missing names appear under "(no subaccount)"), FOCUS RegionName (groupBy=region; missing names appear under "(no region)"), the value of the requested FOCUS Tags key (groupBy=tag; untagged cost appears under "(untagged)"), or the allocation label (groupBy=allocation; cost matching no rule appears under "Unallocated").
	Key string `json:"key"`
}

// SyncLastRun defines model for SyncLastRun.
type SyncLastRun struct {
	// Error Present only when the recorded error is non-empty.
	Error            *string            `json:"error,omitempty"`
	FinishedAt       time.Time          `json:"finishedAt"`
	Outcome          SyncLastRunOutcome `json:"outcome"`
	PeriodsProcessed int64              `json:"periodsProcessed"`
	PeriodsSkipped   int64              `json:"periodsSkipped"`
	RecordsIngested  int64              `json:"recordsIngested"`
	StartedAt        time.Time          `json:"startedAt"`
}

// SyncLastRunOutcome defines model for SyncLastRun.Outcome.
type SyncLastRunOutcome string

// SyncSourceStatus defines model for SyncSourceStatus.
type SyncSourceStatus struct {
	Connector string `json:"connector"`

	// Interval Configured Go duration string, present only for an enabled configured source.
	Interval *string      `json:"interval,omitempty"`
	LastRun  *SyncLastRun `json:"lastRun,omitempty"`

	// LastSuccessAt Last successful finish time in UTC, absent when the source has never succeeded.
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	Name          string     `json:"name"`

	// NextRunAt Next due time in UTC, present only for an enabled configured source.
	NextRunAt *time.Time `json:"nextRunAt,omitempty"`
	Tenant    string     `json:"tenant"`
}

// SyncStatusResponse defines model for SyncStatusResponse.
type SyncStatusResponse struct {
	// Enabled True when this serve process runs scheduled ingestion.
	Enabled bool `json:"enabled"`

	// Sources One entry per source-name and tenant retention key.
	Sources []SyncSourceStatus `json:"sources"`
}

// UnitEconomics defines model for UnitEconomics.
type UnitEconomics struct {
	// Currencies All billing currencies with cost rows in the requested range, sorted ascending. This is the source for a currency selector and is [] (never null) when the range is empty.
	Currencies []string `json:"currencies"`

	// Currency Cost-side BillingCurrency: the currency query parameter when provided, otherwise the alphabetically-first currency in the range, or "" when the range is empty.
	Currency string `json:"currency"`

	// Days Union of cost and metric days, day-ascending.
	Days   []UnitEconomicsDay  `json:"days"`
	Metric string              `json:"metric"`
	Period UnitEconomicsPeriod `json:"period"`

	// Provider FOCUS ServiceProviderName of this response's rows: the provider query parameter when provided, otherwise "".
	Provider string `json:"provider"`

	// Providers All FOCUS ServiceProviderName values with cost rows in the requested range, not scoped by the provider or currency filters, sorted ascending. This is the source for a provider selector and is [] (never null) when the range is empty.
	Providers []string `json:"providers"`
}

// UnitEconomicsDay defines model for UnitEconomicsDay.
type UnitEconomicsDay struct {
	// Cost Exact daily cost when a cost bin exists; any sign is retained.
	Cost *string            `json:"cost,omitempty"`
	Date openapi_types.Date `json:"date"`

	// Quantity Exact daily business quantity when a metric bin exists.
	Quantity *string `json:"quantity,omitempty"`

	// UnitCost Present only for a covered day. cost / quantity rounded to scale 18 with round-half-away-from-zero, trailing zeros trimmed. "0" is a meaningful rounded result and is not omitted.
	UnitCost *string `json:"unitCost,omitempty"`
}

// UnitEconomicsPeriod defines model for UnitEconomicsPeriod.
type UnitEconomicsPeriod struct {
	// Cost Exact cost sum over covered days only.
	Cost string `json:"cost"`

	// CoveredDays Number of days carrying both cost and positive quantity.
	CoveredDays int `json:"coveredDays"`

	// Quantity Exact quantity sum over covered days only.
	Quantity string `json:"quantity"`

	// UnitCost Covered-period cost / quantity at scale 18, round-half-away-from-zero; absent when coveredDays is zero.
	UnitCost *string `json:"unitCost,omitempty"`
}

// GetAnomaliesParams defines parameters for GetAnomalies.
type GetAnomaliesParams struct {
	// Start Inclusive first calendar day (UTC) of the RETURNED flags; it does not affect the scoring baseline. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to score and return. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`

	// GroupBy Cost grouping dimension (the same set as /api/v1/costs/daily).
	GroupBy *GetAnomaliesParamsGroupBy `form:"groupBy,omitempty" json:"groupBy,omitempty"`

	// TagKey Optional FOCUS Tags key whose per-row value becomes the grouping key. Used only with groupBy=tag.
	TagKey *string `form:"tagKey,omitempty" json:"tagKey,omitempty"`

	// Currency Optional three-letter uppercase billing currency whose history to score. Omit to use the alphabetically-first currency in the requested window [start, end], falling back to full history when the window is empty.
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`

	// Provider Optional FOCUS ServiceProviderName whose history to score. Omit to score every provider. Free text at most 8192 bytes; must be non-empty when present.
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
}

// GetAnomaliesParamsGroupBy defines parameters for GetAnomalies.
type GetAnomaliesParamsGroupBy string

// GetDailyCostsParams defines parameters for GetDailyCosts.
type GetDailyCostsParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`

	// GroupBy Cost grouping dimension.
	GroupBy *GetDailyCostsParamsGroupBy `form:"groupBy,omitempty" json:"groupBy,omitempty"`

	// TagKey Optional FOCUS Tags key whose per-row value becomes the grouping key. Used only with groupBy=tag.
	TagKey *string `form:"tagKey,omitempty" json:"tagKey,omitempty"`

	// Currency Optional three-letter uppercase billing currency whose series to return. Omit to use the alphabetically-first currency in the range.
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`

	// Provider Optional FOCUS ServiceProviderName whose rows to include. Omit to include every provider. Free text at most 8192 bytes; must be non-empty when present.
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
}

// GetDailyCostsParamsGroupBy defines parameters for GetDailyCosts.
type GetDailyCostsParamsGroupBy string

// GetCostsSummaryParams defines parameters for GetCostsSummary.
type GetCostsSummaryParams struct {
	// Start Inclusive first calendar day (UTC) of the CURRENT window. Defaults to the full range of stored data. Unbounded start makes the preceding window undefined.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) of the CURRENT window. Defaults to the full range of stored data. Unbounded end makes the preceding window undefined.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`

	// GroupBy Cost grouping dimension (same set as /api/v1/costs/daily).
	GroupBy *GetCostsSummaryParamsGroupBy `form:"groupBy,omitempty" json:"groupBy,omitempty"`

	// TagKey Optional FOCUS Tags key whose per-row value becomes the grouping key. Used only with groupBy=tag.
	TagKey *string `form:"tagKey,omitempty" json:"tagKey,omitempty"`

	// Currency Optional three-letter uppercase billing currency whose summary to return. Omit to use the alphabetically-first currency in the current window.
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`

	// Provider Optional FOCUS ServiceProviderName whose rows to include. Omit to include every provider. Free text at most 8192 bytes; must be non-empty when present.
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
}

// GetCostsSummaryParamsGroupBy defines parameters for GetCostsSummary.
type GetCostsSummaryParamsGroupBy string

// GetDailyUnitEconomicsParams defines parameters for GetDailyUnitEconomics.
type GetDailyUnitEconomicsParams struct {
	// Metric Exact imported business metric name.
	Metric string `form:"metric" json:"metric"`

	// Start Inclusive first UTC calendar day; defaults to unbounded.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last UTC calendar day; defaults to unbounded.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`

	// Currency Optional three-letter uppercase billing currency whose costs to merge with the business metric. Omit to use the alphabetically-first currency in the range.
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`

	// Provider Optional FOCUS ServiceProviderName. Filters ONLY the cost side: business-metric quantities are org-wide, so unit cost under a filter is the selected provider's cost per org-wide unit, and days where only other providers had cost count as uncovered.
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
}

// GetDailyUsageMetricsParams defines parameters for GetDailyUsageMetrics.
type GetDailyUsageMetricsParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetDailyTokensParams defines parameters for GetDailyTokens.
type GetDailyTokensParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Statistical cost anomalies (spikes and dips)
	// (GET /api/v1/anomalies)
	GetAnomalies(w http.ResponseWriter, r *http.Request, params GetAnomaliesParams)
	// List imported business metrics
	// (GET /api/v1/business-metrics)
	GetBusinessMetrics(w http.ResponseWriter, r *http.Request)
	// Daily cost by service, provider, or allocation
	// (GET /api/v1/costs/daily)
	GetDailyCosts(w http.ResponseWriter, r *http.Request, params GetDailyCostsParams)
	// Period cost summary with optional preceding-window comparison
	// (GET /api/v1/costs/summary)
	GetCostsSummary(w http.ResponseWriter, r *http.Request, params GetCostsSummaryParams)
	// Instance metadata
	// (GET /api/v1/meta)
	GetMeta(w http.ResponseWriter, r *http.Request)
	// Scheduled ingestion status
	// (GET /api/v1/sync/status)
	GetSyncStatus(w http.ResponseWriter, r *http.Request)
	// Daily and period unit economics for one business metric
	// (GET /api/v1/unit-economics/daily)
	GetDailyUnitEconomics(w http.ResponseWriter, r *http.Request, params GetDailyUnitEconomicsParams)
	// Daily cost-orphaned usage metrics
	// (GET /api/v1/usage/metrics/daily)
	GetDailyUsageMetrics(w http.ResponseWriter, r *http.Request, params GetDailyUsageMetricsParams)
	// Daily token usage by service
	// (GET /api/v1/usage/tokens/daily)
	GetDailyTokens(w http.ResponseWriter, r *http.Request, params GetDailyTokensParams)
	// Liveness check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAnomalies operation middleware
func (siw *ServerInterfaceWrapper) GetAnomalies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnomaliesParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "groupBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "groupBy", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "groupBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupBy", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagKey", r.URL.Query(), &params.TagKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagKey"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagKey", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "currency" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "currency", r.URL.Query(), &params.Currency, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "currency"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", r.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnomalies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBusinessMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetBusinessMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBusinessMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyCosts operation middleware
func (siw *ServerInterfaceWrapper) GetDailyCosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyCostsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "groupBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "groupBy", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "groupBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupBy", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagKey", r.URL.Query(), &params.TagKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagKey"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagKey", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "currency" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "currency", r.URL.Query(), &params.Currency, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "currency"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", r.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyCosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCostsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetCostsSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCostsSummaryParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "groupBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "groupBy", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "groupBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupBy", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagKey", r.URL.Query(), &params.TagKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagKey"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagKey", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "currency" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "currency", r.URL.Query(), &params.Currency, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "currency"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", r.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCostsSummary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeta operation middleware
func (siw *ServerInterfaceWrapper) GetMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSyncStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyUnitEconomics operation middleware
func (siw *ServerInterfaceWrapper) GetDailyUnitEconomics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyUnitEconomicsParams

	// ------------- Required query parameter "metric" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "metric", r.URL.Query(), &params.Metric, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "metric"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "currency" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "currency", r.URL.Query(), &params.Currency, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "currency"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", r.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyUnitEconomics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyUsageMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetDailyUsageMetrics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyUsageMetricsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyUsageMetrics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyTokens operation middleware
func (siw *ServerInterfaceWrapper) GetDailyTokens(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyTokensParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/anomalies", wrapper.GetAnomalies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/business-metrics", wrapper.GetBusinessMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/costs/daily", wrapper.GetDailyCosts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/costs/summary", wrapper.GetCostsSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/meta", wrapper.GetMeta)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sync/status", wrapper.GetSyncStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/unit-economics/daily", wrapper.GetDailyUnitEconomics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/usage/metrics/daily", wrapper.GetDailyUsageMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/usage/tokens/daily", wrapper.GetDailyTokens)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)

	return m
}
