//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetDailyCostsParamsGroupBy.
const (
	Allocation GetDailyCostsParamsGroupBy = "allocation"
	Provider   GetDailyCostsParamsGroupBy = "provider"
	Service    GetDailyCostsParamsGroupBy = "service"
)

// Valid indicates whether the value is a known member of the GetDailyCostsParamsGroupBy enum.
func (e GetDailyCostsParamsGroupBy) Valid() bool {
	switch e {
	case Allocation:
		return true
	case Provider:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// DailyCost defines model for DailyCost.
type DailyCost struct {
	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// Services Per-group costs, sorted by grouping key.
	Services []ServiceCost `json:"services"`

	// Total Total cost of the day, as a decimal string.
	Total string `json:"total"`
}

// DailyCosts defines model for DailyCosts.
type DailyCosts struct {
	// Currency Billing currency of all listed costs (FOCUS BillingCurrency). Empty when no data matched the requested period.
	Currency string `json:"currency"`

	// Days One entry per calendar day with data, days ascending.
	Days []DailyCost `json:"days"`

	// Total Total cost of the whole period, as a decimal string.
	Total string `json:"total"`
}

// DailyTokenUsage defines model for DailyTokenUsage.
type DailyTokenUsage struct {
	// ConsumedQuantity Total ConsumedQuantity for the day/service/unit, as an exact decimal string — never a float.
	ConsumedQuantity string `json:"consumedQuantity"`

	// ConsumedUnit FOCUS ConsumedUnit (always "Tokens" today).
	ConsumedUnit string `json:"consumedUnit"`

	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// ServiceName FOCUS ServiceName.
	ServiceName string `json:"serviceName"`
}

// DailyUsageMetric defines model for DailyUsageMetric.
type DailyUsageMetric struct {
	// Date The UTC calendar day.
	Date openapi_types.Date `json:"date"`

	// MetricName Frozen metric identifier (a token_type, "web_search_requests", or an opaque line item).
	MetricName string `json:"metricName"`

	// Quantity Total quantity for the day/service/tier/metric/unit, as an exact decimal string — never a float.
	Quantity string `json:"quantity"`

	// ServiceName Service or model identity.
	ServiceName string `json:"serviceName"`

	// ServiceTier Vendor service tier, or "" when the vendor has no tier concept.
	ServiceTier string `json:"serviceTier"`

	// Unit Frozen unit vocabulary: "Tokens", "Requests", or "Unknown".
	Unit string `json:"unit"`
}

// Meta defines model for Meta.
type Meta struct {
	// FocusVersion FOCUS specification version the internal model targets (decision D4).
	FocusVersion string `json:"focusVersion"`

	// Name Service name.
	Name string `json:"name"`

	// Version Version of the running Costroid binary.
	Version string `json:"version"`
}

// ServiceCost defines model for ServiceCost.
type ServiceCost struct {
	// Cost Cost total, as a decimal string.
	Cost string `json:"cost"`

	// Key Grouping key: FOCUS ServiceName (groupBy=service), FOCUS ServiceProviderName (groupBy=provider), or the allocation label (groupBy=allocation; cost matching no rule appears under "Unallocated").
	Key string `json:"key"`
}

// GetDailyCostsParams defines parameters for GetDailyCosts.
type GetDailyCostsParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`

	// GroupBy Cost grouping dimension.
	GroupBy *GetDailyCostsParamsGroupBy `form:"groupBy,omitempty" json:"groupBy,omitempty"`
}

// GetDailyCostsParamsGroupBy defines parameters for GetDailyCosts.
type GetDailyCostsParamsGroupBy string

// GetDailyUsageMetricsParams defines parameters for GetDailyUsageMetrics.
type GetDailyUsageMetricsParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// GetDailyTokensParams defines parameters for GetDailyTokens.
type GetDailyTokensParams struct {
	// Start Inclusive first calendar day (UTC) to include. Defaults to the full range of stored data.
	Start *openapi_types.Date `form:"start,omitempty" json:"start,omitempty"`

	// End Inclusive last calendar day (UTC) to include. Defaults to the full range of stored data.
	End *openapi_types.Date `form:"end,omitempty" json:"end,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Daily cost by service, provider, or allocation
	// (GET /api/v1/costs/daily)
	GetDailyCosts(w http.ResponseWriter, r *http.Request, params GetDailyCostsParams)
	// Instance metadata
	// (GET /api/v1/meta)
	GetMeta(w http.ResponseWriter, r *http.Request)
	// Daily cost-orphaned usage metrics
	// (GET /api/v1/usage/metrics/daily)
	GetDailyUsageMetrics(w http.ResponseWriter, r *http.Request, params GetDailyUsageMetricsParams)
	// Daily token usage by service
	// (GET /api/v1/usage/tokens/daily)
	GetDailyTokens(w http.ResponseWriter, r *http.Request, params GetDailyTokensParams)
	// Liveness check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDailyCosts operation middleware
func (siw *ServerInterfaceWrapper) GetDailyCosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyCostsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "groupBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "groupBy", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "groupBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupBy", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyCosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeta operation middleware
func (siw *ServerInterfaceWrapper) GetMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyUsageMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetDailyUsageMetrics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyUsageMetricsParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyUsageMetrics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDailyTokens operation middleware
func (siw *ServerInterfaceWrapper) GetDailyTokens(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDailyTokensParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDailyTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/costs/daily", wrapper.GetDailyCosts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/meta", wrapper.GetMeta)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/usage/metrics/daily", wrapper.GetDailyUsageMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/usage/tokens/daily", wrapper.GetDailyTokens)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)

	return m
}
