// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Costroid Authors

package focuscsv

import "github.com/Costroid/costroid/internal/focus"

// The FOCUS Column ID tables below were generated by reading each column's
// `## Column ID` section (and the Content-Constraints "Feature level" row for
// the Mandatory subsets) from the spec column .md files at the version tags —
// NOT from the lowercase file names (at v1.0 provider.md → ProviderName,
// publisher.md → PublisherName, invoiceissuer.md → InvoiceIssuerName):
//
//	1.0: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/v1.0/specification/columns
//	1.1: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/v1.1/specification/columns
//	1.2: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/v1.2/specification/columns
//	1.3: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/v1.3/specification/datasets/cost_and_usage/columns
//	1.4: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/v1.4/specification/datasets/cost_and_usage/columns
//
// (1.0/1.1/1.2 use the flat pre-1.3 specification/columns/ path — use tag v1.0,
// NOT 1.0-cr, whose consumedunit.md carries a Column-ID typo; some 1.0/1.1 files
// are CRLF, so trailing \r is trimmed. 1.3+ moved columns under
// specification/datasets/cost_and_usage/columns/.)
//
// Pinned counts (asserted in the tests): known 43 / 50 / 57 / 65 / 65;
// Mandatory-presence 21 / 21 / 21 / 23 / 21. FOCUS 1.0 ⊂ 1.1 ⊂ 1.2 with ZERO
// renames and ZERO removals (1.1 = 1.0 + 7 columns), and the 1.0/1.1/1.2
// Mandatory-presence sets are byte-identical. Between 1.3 and 1.4 zero columns
// were renamed (63 shared byte-identical); 1.4 removed ProviderName and
// PublisherName and added the nullable Conditional
// CommitmentProgramEligibilityDetails and InvoiceDetailId.

// knownColumns10 is the full sorted Column ID list at FOCUS v1.0 (43) — a strict
// subset of knownColumns12 (= knownColumns12 minus 14 columns: BillingAccountType,
// CapacityReservationId, CapacityReservationStatus, CommitmentDiscountQuantity,
// CommitmentDiscountUnit, InvoiceId, PricingCurrency,
// PricingCurrencyContractedUnitPrice, PricingCurrencyEffectiveCost,
// PricingCurrencyListUnitPrice, ServiceSubcategory, SkuMeter, SkuPriceDetails,
// SubAccountType).
var knownColumns10 = []string{
	"AvailabilityZone", "BilledCost", "BillingAccountId", "BillingAccountName", "BillingCurrency",
	"BillingPeriodEnd", "BillingPeriodStart", "ChargeCategory", "ChargeClass", "ChargeDescription",
	"ChargeFrequency", "ChargePeriodEnd", "ChargePeriodStart", "CommitmentDiscountCategory",
	"CommitmentDiscountId", "CommitmentDiscountName", "CommitmentDiscountStatus", "CommitmentDiscountType",
	"ConsumedQuantity", "ConsumedUnit", "ContractedCost", "ContractedUnitPrice", "EffectiveCost",
	"InvoiceIssuerName", "ListCost", "ListUnitPrice", "PricingCategory", "PricingQuantity", "PricingUnit",
	"ProviderName", "PublisherName", "RegionId", "RegionName", "ResourceId", "ResourceName", "ResourceType",
	"ServiceCategory", "ServiceName", "SkuId", "SkuPriceId", "SubAccountId", "SubAccountName", "Tags",
}

// knownColumns11 is the full sorted Column ID list at FOCUS v1.1 (50) —
// knownColumns10 plus 7 columns (CapacityReservationId, CapacityReservationStatus,
// CommitmentDiscountQuantity, CommitmentDiscountUnit, ServiceSubcategory, SkuMeter,
// SkuPriceDetails), still a strict subset of knownColumns12 with zero renames.
var knownColumns11 = []string{
	"AvailabilityZone", "BilledCost", "BillingAccountId", "BillingAccountName", "BillingCurrency",
	"BillingPeriodEnd", "BillingPeriodStart", "CapacityReservationId", "CapacityReservationStatus",
	"ChargeCategory", "ChargeClass", "ChargeDescription", "ChargeFrequency", "ChargePeriodEnd",
	"ChargePeriodStart", "CommitmentDiscountCategory", "CommitmentDiscountId", "CommitmentDiscountName",
	"CommitmentDiscountQuantity", "CommitmentDiscountStatus", "CommitmentDiscountType", "CommitmentDiscountUnit",
	"ConsumedQuantity", "ConsumedUnit", "ContractedCost", "ContractedUnitPrice", "EffectiveCost",
	"InvoiceIssuerName", "ListCost", "ListUnitPrice", "PricingCategory", "PricingQuantity", "PricingUnit",
	"ProviderName", "PublisherName", "RegionId", "RegionName", "ResourceId", "ResourceName", "ResourceType",
	"ServiceCategory", "ServiceName", "ServiceSubcategory", "SkuId", "SkuMeter", "SkuPriceDetails", "SkuPriceId",
	"SubAccountId", "SubAccountName", "Tags",
}

// knownColumns12 is the full sorted Column ID list at FOCUS v1.2 (57).
var knownColumns12 = []string{
	"AvailabilityZone", "BilledCost", "BillingAccountId", "BillingAccountName", "BillingAccountType",
	"BillingCurrency", "BillingPeriodEnd", "BillingPeriodStart", "CapacityReservationId", "CapacityReservationStatus",
	"ChargeCategory", "ChargeClass", "ChargeDescription", "ChargeFrequency", "ChargePeriodEnd", "ChargePeriodStart",
	"CommitmentDiscountCategory", "CommitmentDiscountId", "CommitmentDiscountName", "CommitmentDiscountQuantity",
	"CommitmentDiscountStatus", "CommitmentDiscountType", "CommitmentDiscountUnit", "ConsumedQuantity", "ConsumedUnit",
	"ContractedCost", "ContractedUnitPrice", "EffectiveCost", "InvoiceId", "InvoiceIssuerName", "ListCost",
	"ListUnitPrice", "PricingCategory", "PricingCurrency", "PricingCurrencyContractedUnitPrice",
	"PricingCurrencyEffectiveCost", "PricingCurrencyListUnitPrice", "PricingQuantity", "PricingUnit",
	"ProviderName", "PublisherName", "RegionId", "RegionName", "ResourceId", "ResourceName", "ResourceType",
	"ServiceCategory", "ServiceName", "ServiceSubcategory", "SkuId", "SkuMeter", "SkuPriceDetails", "SkuPriceId",
	"SubAccountId", "SubAccountName", "SubAccountType", "Tags",
}

// knownColumns13 is the full sorted Column ID list at FOCUS v1.3 (65).
var knownColumns13 = []string{
	"AllocatedMethodDetails", "AllocatedMethodId", "AllocatedResourceId", "AllocatedResourceName", "AllocatedTags",
	"AvailabilityZone", "BilledCost", "BillingAccountId", "BillingAccountName", "BillingAccountType",
	"BillingCurrency", "BillingPeriodEnd", "BillingPeriodStart", "CapacityReservationId", "CapacityReservationStatus",
	"ChargeCategory", "ChargeClass", "ChargeDescription", "ChargeFrequency", "ChargePeriodEnd", "ChargePeriodStart",
	"CommitmentDiscountCategory", "CommitmentDiscountId", "CommitmentDiscountName", "CommitmentDiscountQuantity",
	"CommitmentDiscountStatus", "CommitmentDiscountType", "CommitmentDiscountUnit", "ConsumedQuantity", "ConsumedUnit",
	"ContractApplied", "ContractedCost", "ContractedUnitPrice", "EffectiveCost", "HostProviderName", "InvoiceId",
	"InvoiceIssuerName", "ListCost", "ListUnitPrice", "PricingCategory", "PricingCurrency",
	"PricingCurrencyContractedUnitPrice", "PricingCurrencyEffectiveCost", "PricingCurrencyListUnitPrice",
	"PricingQuantity", "PricingUnit", "ProviderName", "PublisherName", "RegionId", "RegionName", "ResourceId",
	"ResourceName", "ResourceType", "ServiceCategory", "ServiceName", "ServiceProviderName", "ServiceSubcategory",
	"SkuId", "SkuMeter", "SkuPriceDetails", "SkuPriceId", "SubAccountId", "SubAccountName", "SubAccountType", "Tags",
}

// knownColumns14 is the full sorted Column ID list at FOCUS v1.4 (65).
var knownColumns14 = []string{
	"AllocatedMethodDetails", "AllocatedMethodId", "AllocatedResourceId", "AllocatedResourceName", "AllocatedTags",
	"AvailabilityZone", "BilledCost", "BillingAccountId", "BillingAccountName", "BillingAccountType",
	"BillingCurrency", "BillingPeriodEnd", "BillingPeriodStart", "CapacityReservationId", "CapacityReservationStatus",
	"ChargeCategory", "ChargeClass", "ChargeDescription", "ChargeFrequency", "ChargePeriodEnd", "ChargePeriodStart",
	"CommitmentDiscountCategory", "CommitmentDiscountId", "CommitmentDiscountName", "CommitmentDiscountQuantity",
	"CommitmentDiscountStatus", "CommitmentDiscountType", "CommitmentDiscountUnit", "CommitmentProgramEligibilityDetails",
	"ConsumedQuantity", "ConsumedUnit", "ContractApplied", "ContractedCost", "ContractedUnitPrice", "EffectiveCost",
	"HostProviderName", "InvoiceDetailId", "InvoiceId", "InvoiceIssuerName", "ListCost", "ListUnitPrice",
	"PricingCategory", "PricingCurrency", "PricingCurrencyContractedUnitPrice", "PricingCurrencyEffectiveCost",
	"PricingCurrencyListUnitPrice", "PricingQuantity", "PricingUnit", "RegionId", "RegionName", "ResourceId",
	"ResourceName", "ResourceType", "ServiceCategory", "ServiceName", "ServiceProviderName", "ServiceSubcategory",
	"SkuId", "SkuMeter", "SkuPriceDetails", "SkuPriceId", "SubAccountId", "SubAccountName", "SubAccountType", "Tags",
}

// mandatory12 is the sorted Mandatory-presence set at FOCUS v1.2 (21). A
// column being Mandatory means its header MUST be present; several of these
// (ChargeClass, ChargeDescription, PricingQuantity, PricingUnit) still allow
// nulls — presence, not not-null, is what this set gates.
var mandatory12 = []string{
	"BilledCost", "BillingAccountId", "BillingAccountName", "BillingCurrency", "BillingPeriodEnd",
	"BillingPeriodStart", "ChargeCategory", "ChargeClass", "ChargeDescription", "ChargePeriodEnd",
	"ChargePeriodStart", "ContractedCost", "EffectiveCost", "InvoiceIssuerName", "ListCost",
	"PricingQuantity", "PricingUnit", "ProviderName", "PublisherName", "ServiceCategory", "ServiceName",
}

// mandatory13 is the sorted Mandatory-presence set at FOCUS v1.3 (23): the
// 1.2 set plus HostProviderName and ServiceProviderName (ProviderName and
// PublisherName remain Mandatory in 1.3, removed only in 1.4).
var mandatory13 = []string{
	"BilledCost", "BillingAccountId", "BillingAccountName", "BillingCurrency", "BillingPeriodEnd",
	"BillingPeriodStart", "ChargeCategory", "ChargeClass", "ChargeDescription", "ChargePeriodEnd",
	"ChargePeriodStart", "ContractedCost", "EffectiveCost", "HostProviderName", "InvoiceIssuerName",
	"ListCost", "PricingQuantity", "PricingUnit", "ProviderName", "PublisherName", "ServiceCategory",
	"ServiceName", "ServiceProviderName",
}

// notNull14 is the sorted subset of the 21 FOCUS 1.4 Mandatory columns that
// are ALSO non-null (15) — the exact set the pipeline's validation enforces
// row by row (validate.go). A 1.4-declared file must carry all of these.
var notNull14 = []string{
	"BilledCost", "BillingAccountId", "BillingCurrency", "BillingPeriodEnd", "BillingPeriodStart",
	"ChargeCategory", "ChargePeriodEnd", "ChargePeriodStart", "ContractedCost", "EffectiveCost",
	"InvoiceIssuerName", "ListCost", "ServiceCategory", "ServiceName", "ServiceProviderName",
}

// mandatoryNullable14 is the sorted remainder of the 21 FOCUS 1.4 Mandatory
// columns — Mandatory-presence but nullable (6). Their absence from a 1.4
// file is a WARNING, not a failure.
var mandatoryNullable14 = []string{
	"BillingAccountName", "ChargeClass", "ChargeDescription", "HostProviderName", "PricingQuantity", "PricingUnit",
}

// knownColumnsFor returns the known-column set for a supported version. Every
// accepted version needs an explicit case: the default arm returns the 65-column
// 1.4 set (knownColumns14), a superset — so a 1.0/1.1 file falling through to it
// would wrongly accept columns absent from its declared version (e.g. InvoiceId,
// first added in 1.2, or ServiceProviderName, added in 1.3) as known.
func knownColumnsFor(v focus.Version) map[string]struct{} {
	switch v {
	case focus.V1_0:
		return toSet(knownColumns10)
	case focus.V1_1:
		return toSet(knownColumns11)
	case focus.V1_2:
		return toSet(knownColumns12)
	case focus.V1_3:
		return toSet(knownColumns13)
	default: // V1_4 (ParseVersion has already rejected everything else)
		return toSet(knownColumns14)
	}
}

// mandatoryFor returns the sorted Mandatory-presence set for a 1.0/1.1/1.2/1.3
// file (1.4 uses notNull14 + mandatoryNullable14 directly). FOCUS 1.0, 1.1, and
// 1.2 share the SAME 21-column Mandatory set byte-for-byte (verified against the
// v1.0/v1.1 tags: ProviderName/PublisherName are Mandatory in all three and
// 1.0/1.1 carry none of 1.3's added Mandatory columns), so all three resolve to
// mandatory12. Every non-1.2 case needs an explicit arm: 1.0/1.1 must NOT fall
// through to mandatory13 (23 columns), which requires the 1.3-only successors.
func mandatoryFor(v focus.Version) []string {
	switch v {
	case focus.V1_0, focus.V1_1, focus.V1_2:
		return mandatory12
	default: // V1_3
		return mandatory13
	}
}

func toSet(cols []string) map[string]struct{} {
	set := make(map[string]struct{}, len(cols))
	for _, c := range cols {
		set[c] = struct{}{}
	}
	return set
}
