// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Costroid Authors
//
// Code generated by internal/demofixtures; DO NOT EDIT.
// Regenerate with `make demo-fixtures`.
//
// Demo-mode preset date ranges, pinned to the capture asOf (never the
// visitor's wall clock). A backendless demo can only serve the ranges whose
// fixtures were captured, so the date control offers these presets.

export type DemoPresetId = "last30" | "last90" | "full";

export type DemoPreset = {
  id: DemoPresetId;
  label: string;
  start: string;
  end: string;
};

export const DEMO_PRESETS: DemoPreset[] = [
  { id: "last30", label: "Last 30 days", start: "2026-06-12", end: "2026-07-11" },
  { id: "last90", label: "Last 90 days", start: "2026-04-13", end: "2026-07-11" },
  { id: "full", label: "Full window", start: "2026-01-12", end: "2026-07-11" },
];
